### ISSUE TITLE
bannerView点击崩溃

### ISSUE THREAD

**Issue by Dkaishu** [nyakokishi/ZhihuDaily#2]
bannerView点击事件没处理好啊，怎么做合适 @nyakokishi

**Comment by nyakokishi** [comment]
@Dkaishu 现在暂时修复这个问题，具体可以看最新的 commit ，太久没维护这个项目了，现在来看自己之前写的代码就觉得实在是不堪入目了（说明这段时间我也是有进步的），近期会考虑重构。加油⛽️

**Comment by Dkaishu** [comment]
辛苦了，加油！
